### ISSUE TITLE
axis.geo(abbr = TRUE ) not working as intended

### ISSUE THREAD

**Issue by rnfelice** [palaeoverse-community/palaeoverse-quarto#3]
It seems that setting `abbr= TRUE` on `axis.geo()` has no effect. I think that the problem might be that `palaeoverse::time_bins(scale = "GTS2020"` does not have an "abbr" column unlike `deeptime::get_scale_data()`.  might be usefully to have the abbreviations in the built in time bin data

**Comment by willgearty** [comment]
@rnfelice Thanks for reporting this, but this repository is for our website. Please report your issue to https://github.com/palaeoverse-community/palaeoverse/issues. Thanks!

**Comment by willgearty** [comment]
I looked into this, and `abbr = TRUE` is the default for `axis_geo()`. Setting `abbr = FALSE` works for me fine. If you continue to encounter this issue, please post an issue with a reproducible example to our [palaeoverse repository](https://github.com/palaeoverse-community/palaeoverse/issues).
